Repository group-patronage/group-patronage, pull requests merged in 2023-06, with the labels that each got.

#70 Lazy loading implemented
  client/src/App.jsx
  client/src/pages/index.js
Labels: GSSoC'23

#85 Optimizing the getCampaigns function
  myWeb3ProjectOne/contracts/CrowdFunding.sol
Labels: gssoc23, level2

#75 Added Withdrawal Mechanism.
  myWeb3ProjectOne/contracts/CrowdFunding.sol
Labels: gssoc23, level3

#42 Add fallback and receive function
  myWeb3ProjectOne/contracts/CrowdFunding.sol
Labels: gssoc23, level3

#15 Added support for erc20 tokens
  myWeb3ProjectOne/contracts/CrowdFunding.sol
Labels: gssoc23, level3

#92 hover effect added on let's start
  client/src/pages/LandingPage.jsx
  node_modules/.package-lock.json
  package-lock.json
Labels: gssoc23, level1

#97 Typewriter effect add in Landing page issue#89 resolved
  client/package-lock.json
  client/package.json
  client/src/pages/LandingPage.jsx
Labels: level1

#96 #94 Bot added
  .github/workflows/close_old_issues.yaml
Labels: gssoc23, level2

#108 Converted PNG to WebP
  client/src/assets/ava.png
  client/src/assets/ava.webp
  client/src/assets/bin.png
  client/src/assets/bin.webp
  client/src/assets/btc.png
  client/src/assets/btc.webp
  client/src/assets/eth.png
  client/src/assets/eth.webp
  client/src/assets/favicon.png
  client/src/assets/favicon.webp
  client/src/assets/github.png
  client/src/assets/github.webp
  client/src/assets/homeIcon.png
  client/src/assets/homeIcon.webp
  client/src/assets/image2.png
  client/src/assets/image2.webp
  client/src/assets/image3.png
  client/src/assets/image3.webp
  client/src/assets/image4.png
  client/src/assets/image4.webp
  client/src/assets/image5.png
  client/src/assets/image5.webp
  client/src/assets/index.js
  client/src/assets/surveyIcon.png
  client/src/assets/surveyIcon.webp
  client/src/assets/thirdweb.png
  client/src/assets/thirdweb.webp
  client/src/pages/LandingPage.jsx
Labels: gssoc23, level2
