Repository group-patronage/group-patronage, pull requests merged in 2023-07, with the labels that each got.

#117 Added meta tags
  client/index.html
Labels: gssoc23, level2

#118 Lazy loading to images added
  client/src/components/DisplayCampaigns.jsx
  client/src/components/FundCard.jsx
  client/src/components/Loader.jsx
  client/src/components/Navbar.jsx
  client/src/components/Sidebar.jsx
  client/src/components/StartingLoader.jsx
  client/src/components/SurveyCard.jsx
  client/src/pages/CampaignDetails.jsx
  client/src/pages/LandingPage.jsx
Labels: gssoc23, level2

#116 Hover effect added on let's start button
  client/hardhat-javascript-starter/.gitignore
  client/hardhat-javascript-starter/README.md
  client/hardhat-javascript-starter/contracts/Contract.sol
  client/hardhat-javascript-starter/hardhat.config.js
  client/hardhat-javascript-starter/package-lock.json
  client/hardhat-javascript-starter/package.json
  client/hardhat-javascript-starter/yarn.lock
  client/src/pages/LandingPage.jsx
Labels: gssoc23, level1

#121 Added styling on the scrollbar
  client/src/index.css
Labels: gssoc23, level2

#47 Added Responsive Design to Website for Smaller Devices
  client/src/components/FundCard.jsx
  client/src/components/SurveyCard.jsx
  client/src/pages/AllCampaigns.jsx
  client/src/pages/AllSurveys.jsx
  client/src/pages/CampaignDetails.jsx
  client/src/pages/CreateCampaign.jsx
  client/src/pages/Home.jsx
  client/src/pages/LandingPage.jsx
  client/tailwind.config.js
Labels: gssoc23, level3

#125 Fix Logout Redirect Issue and Add Vercel Configuration
  client/src/pages/LoginPage.jsx
  client/vercel.json
Labels: gssoc23, level1

#124 added hover effect on Connect, Create a new survey and Submit new campaign
  client/src/components/Navbar.jsx
  client/src/pages/AllSurveys.jsx
  client/src/pages/CreateCampaign.jsx
Labels: gssoc23, level1

#132 Enhanced the scrollbar
  client/src/index.css
Labels: gssoc23, level1

#128 Responsive work done
  client/src/App.jsx
  client/src/components/SurveyCard.jsx
  client/src/pages/LandingPage.jsx
  client/tailwind.config.js
Labels: gssoc23, level2

#140 fix: wrong redirection when clicking log-out button
  client/src/constants/index.js
Labels: gssoc23, level1

#139 Update README.md
  README.md
Labels: gssoc23, level1

#143 Added a licenses section and a MIT licenses badge
  README.md
Labels: gssoc23, level1

#146 Added aria attributes to start campaign form
  client/src/components/CustomButton.jsx
  client/src/components/FormField.jsx
  client/src/pages/CreateCampaign.jsx
Labels: gssoc23, level3

#147 added search functionality
  client/src/components/DisplayCampaigns.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Home.jsx
Labels: gssoc23, level3

#148 fixed hovering text
  client/src/components/Sidebar.jsx
Labels: gssoc23, level1

#149 feat: make social anchors and buttons accessible ✨
  client/src/components/Navbar.jsx
  client/src/components/Sidebar.jsx
Labels: gssoc23, level2

#150 Made card responsive
  client/src/components/DisplayCampaigns.jsx
  client/src/components/FundCard.jsx
Labels: gssoc23, level2

#155 fixed logo
  client/src/components/Navbar.jsx
  client/src/components/Sidebar.jsx
Labels: gssoc23, level1

#156 fixed start a campaign heading
  client/src/pages/CreateCampaign.jsx
Labels: gssoc23, level1

#162 Removed Google Credentials from console and Generated ID for debugging user
  client/src/components/Navbar.jsx
Labels: gssoc23, level1

#159 fixed search bar visibility
  client/src/components/Navbar.jsx
  client/src/pages/AllCampaigns.jsx
  client/src/pages/AllSurveys.jsx
  client/src/pages/CreateCampaign.jsx
  client/src/pages/Home.jsx
Labels: gssoc23, level2

#160 added create a survey page
  client/src/App.jsx
  client/src/pages/AllSurveys.jsx
  client/src/pages/CreateSurveys.jsx
Labels: gssoc23, level3

#175 added not found text
  client/src/components/DisplayCampaigns.jsx
Labels: gssoc23, level1

#176 Hovering Effects on Button
  client/src/components/CustomButton.jsx
  client/src/components/Navbar.jsx
  client/src/pages/AllSurveys.jsx
  client/src/pages/CreateCampaign.jsx
Labels: gssoc23, level1

#177 fixed create urvey button
  client/src/components/CustomButton.jsx
  client/src/pages/AllSurveys.jsx
Labels: gssoc23, level1

#179 fix: logo visibility on page 🛠
  client/src/components/Navbar.jsx
  client/src/components/Sidebar.jsx
Labels: gssoc23, level1

#183 feat: init GitHub workflow ✨
  .github/workflows/Changelog.yml
Labels: gssoc23, level1

#184 feat: init commitlint into Project 🎉
  .husky/commit-msg
  commitlint.config.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: gssoc23, level1

#185 feat: add pr author auto assign workflow 🤖
  .github/workflows/author-assign.yml
Labels: gssoc23, level1

#186 issue-182
  client/src/components/SurveyCard.jsx
Labels: gssoc23, level1

#200 Enhanced README.md
  README.md
Labels: gssoc23, level1

#196 fixed placeholder in search
  client/src/pages/CampaignDetails.jsx
  package.json
Labels: gssoc23, level1
